### ISSUE TITLE
Persist State of Results in URL for Advanced Tab

### ISSUE THREAD

**Issue by prayashm** [prayashm/cet-results-mirror#3]
Currently, the advanced tab works great to have an overview of entire class's marks.
It would be nice to have a feature to persist the state of the advanced marks being accessed in the URL.
This will allow the URLs to be shareable.

e.g. https://results.cetb.in/overview?branch=IT&batch=2017&sem=7

**Comment by vozille** [comment]
this can be best achieved by returning rendered html templates from each function.
Eg 
https://results.cetb.in/result/IT/2017/7 will call
`@app.route("result/<branch>/<batch>/<semester>")
def handle()`
